name: Trigger Workflow in other account's repository

on:
  push:
    branches:
      - dev

jobs:
  dispatch_to_other:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to other Rep
        env:
          REPO_B_OWNER: gagandeep3458
          REPO_B_NAME: BuilderProject
          GITHUB_TOKEN: ${{ secrets.OTHER_REPO_DISPATCH_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/gagandeep3458/BuilderProject/dispatches \
            -d '{"event_type": "trigger_workflow_a", "client_payload": {"branch": "${{ github.ref_name }}" , "r_name" : "DummyProject1", "b_name" : "dev"}}'
